version: "3"
services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${POSTGRES_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRES_ADMIN_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"

volumes:
  postgres_data:
